site_name: DNIT - Educação paro o trânsito
repo_name: "2023.2-DNIT-DOC"
repo_url: https://github.com/fga-eps-mds/2023.2-Dnit-DOC

docs_dir: docs

theme:
  name: material
  language: pt
  features:
           - navigation.tabs
  logo: assets/logos/dnitLogoBranco.png
  favicon: assets/logos/dnitLogoBrancoFundoAzul.png

nav:
  - Home: 
    - Início: index.md
    - Guia de contribuição: CONTRIBUTING.md
    - Código de conduta:  CODE_OF_CONDUCT.md
  - Plano e monitoramento:
    - Plano de comunicação: plano-monitoramento/plano-comunicacao.md
    - Plano de custos: plano-monitoramento/plano-custos.md
    - Plano de qualidade: plano-monitoramento/plano-qualidade.md
  - Documentos do projeto:
    - Metodologias: documentos-projeto/metodologias.md
    - Identidade Visual: documentos-projeto/identidade.md
  - Andamento:
    - Pré-sprints:
      - Semana 1: andamento/semana1.md
      - Semana 2: andamento/semana2.md
      - Semana 3: andamento/semana3.md
      - Semana 4: andamento/semana4.md
      - Semana 5: andamento/semana5.md
      - Semana 6: andamento/semana6.md
    - Sprints:
      - Sprint Teste: andamento/sprint-teste.md

# Pra mais informações sobre personalizar cores
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
extra_css:
  - stylesheets/extra.css
